from __future__ import annotations

MARKET_MAPPING_FIELDS = [
    "match_id",
    "team_a",
    "team_b",
    "kickoff_time",
    "polymarket_market_id",
    "polymarket_slug",
    "condition_id",
    "token_id_team_a_win",
    "token_id_draw",
    "token_id_team_b_win",
    "outcome_label_team_a",
    "outcome_label_draw",
    "outcome_label_team_b",
    "mapping_confidence",
    "mapping_status",
    "reviewed_by_user",
    "last_checked_at",
]

REAL_TRADE_FIELDS = [
    "trade_id",
    "created_at",
    "match_id",
    "team_a",
    "team_b",
    "market_id",
    "condition_id",
    "token_id",
    "outcome",
    "country_or_draw",
    "side",
    "limit_price",
    "stake_usd",
    "shares_requested",
    "order_id",
    "order_status",
    "filled_shares",
    "average_fill_price",
    "status",
    "error_message",
    "settled_at",
    "actual_result",
    "payout",
    "profit_loss",
    "roi",
]

RECOMMENDATION_FIELDS = [
    "trade_id",
    "created_at",
    "match_id",
    "team_a",
    "team_b",
    "market_id",
    "condition_id",
    "token_id",
    "outcome",
    "country_or_draw",
    "model_probability",
    "market_entry_price",
    "edge",
    "expected_value",
    "spread",
    "liquidity",
    "recommended_stake_usd",
    "stake_reason",
    "approved_by_risk",
    "risk_reason",
    "risk_checks",
    "status",
]
